apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-nginx-{{ .Values.ns }}
    namespace: {{ .Values.ns }}
spec:
    selector:
      matchLabels:
         run: my-nginx-{{ .Values.ns }}
    replicas: {{ .Values.replicas }}
    template:
      metadata:
        labels:
          run: my-nginx-{{ .Values.ns }}
      spec:
        containers: 
        - name: my-nginx-{{ .Values.ns }}
          image: nginx
          ports:
          - containerPort: 80


