apiVersion: v1
kind: Service
metadata:
    name: my-nginx
    namespace: {{ .Values.ns }}
    labels:
      run: my-nginx
spec:
   ports:
   - port: {{ .Values.port }}
     targetPort: 80
     protocol: TCP
   selector:
        run: my-nginx
   type: LoadBalancer
